travis:
  secure:
    BINSTAR_TOKEN: wifXy2G6V5VnlL2O3pkZWSrEkaECXLJYkgZa8mAPeiuUMZzMKYYIdTF03jdMkCA6PnBYuDmF6ouvihk0fFaeHnz/43LmKda5o00h6WiNVslE3BQiK5zGzhSdAUB8I16z5otrbW2KbHJ2g4aI5/bI1CbcCvmusxdxRLXdUP8T9Y1Cl7kNCRkLoScsXd2YR3IzzEKd3RDL/KNDXk3RMIy7CyD5DDQAokS6zONwEV05Xjyljz3A7c1j4O1DF6/FTr8xrrCmVc7eIzMuu1wP2JzReL8VRkNtLEr6CzMHoNCP/1HLl3CjNZ4ZbrMiK4SWKqPI8IOtujeTaahylWuwRHXhFh6wAsiN7raWEJzvg0oFuXXmYi2sPnlMj7bEEMIQFf1qNDqbL9EjOH79sk7cQCj2bHZlXN45cpyQdomkgw/3/4Rt6fEHviVOGLerxgfs7fygG0Hb8OyLlSC0dYwoWbd7UhxZd/80KU6wNHV9JNFmhWaPGxzCPNLIs7J3kpFYEMR+VLtnmivSDOr2xSxygSSq9KaNOWjOkb89kCXQctwC2JXoh+CbqygDAfbSDa+FMMoxB8wmA+yKqjbjN0/eSD1J40vzk9bj7JZYsG+CYYv/VNyUNejeEXUmtzK/UtwLZnhykoNMubWj6b2+cHCxmbOp3thXXK01kAn0BOzYLuZDmpU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
